WEATHER_API_URL = http://api.openweathermap.org/data/2.5/weather?q={city}&APPID={appid}
APP_ID=Aanvragen!

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect